services:
  db:
    image: postgres:16.3-alpine
    container_name: app_lucasdonordeste_db
    volumes:
      - pg_app_lucasdonordeste:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  pg_app_lucasdonordeste:
